package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

/**
 * AccountRecommendLog generated by hbm2java
 */
@Alias("account_recommend_log")
public class AccountRecommendLog implements java.io.Serializable {
	private Integer recommend_log_id;
	@NotNull
	private int from_user_id;
	@NotNull
	private int to_user_id;
	@NotNull
	private String from_user_name;
	@NotNull
	private String to_user_name;
	@NotNull
	private short seq_no;
	@NotNull
	private BigDecimal recommend_amount;
	@NotNull
	private String donate_status;
	private String process_user;
	private Date process_time;
	@DateTimeFormat(pattern = "yyyy-mm-dd hh:MM:ss")
	private Date update_time;
	@NotNull
	@DateTimeFormat(pattern = "yyyy-mm-dd hh:MM:ss")
	private Date create_time;

	public AccountRecommendLog() {
	}

	public AccountRecommendLog(Integer recommend_log_id, int from_user_id, int to_user_id, String from_user_name, String to_user_name, short seq_no, BigDecimal recommend_amount, String donate_status, String process_user, Date process_time, Date update_time, Date create_time) {
		this.recommend_log_id = recommend_log_id;
		this.from_user_id = from_user_id;
		this.to_user_id = to_user_id;
		this.from_user_name = from_user_name;
		this.to_user_name = to_user_name;
		this.seq_no = seq_no;
		this.recommend_amount = recommend_amount;
		this.donate_status = donate_status;
		this.process_user = process_user;
		this.process_time = process_time;
		this.update_time = update_time;
		this.create_time = create_time;
	}

	public Integer getRecommend_log_id() {
		return recommend_log_id;
	}

	public void setRecommend_log_id(Integer recommend_log_id) {
		this.recommend_log_id = recommend_log_id;
	}

	public int getFrom_user_id() {
		return from_user_id;
	}

	public void setFrom_user_id(int from_user_id) {
		this.from_user_id = from_user_id;
	}

	public int getTo_user_id() {
		return to_user_id;
	}

	public void setTo_user_id(int to_user_id) {
		this.to_user_id = to_user_id;
	}

	public String getFrom_user_name() {
		return from_user_name;
	}

	public void setFrom_user_name(String from_user_name) {
		this.from_user_name = from_user_name;
	}

	public String getTo_user_name() {
		return to_user_name;
	}

	public void setTo_user_name(String to_user_name) {
		this.to_user_name = to_user_name;
	}

	public short getSeq_no() {
		return seq_no;
	}

	public void setSeq_no(short seq_no) {
		this.seq_no = seq_no;
	}

	public BigDecimal getRecommend_amount() {
		return recommend_amount;
	}

	public void setRecommend_amount(BigDecimal recommend_amount) {
		this.recommend_amount = recommend_amount;
	}

	public String getDonate_status() {
		return donate_status;
	}

	public void setDonate_status(String donate_status) {
		this.donate_status = donate_status;
	}

	public String getProcess_user() {
		return process_user;
	}

	public void setProcess_user(String process_user) {
		this.process_user = process_user;
	}

	public Date getProcess_time() {
		return process_time;
	}

	public void setProcess_time(Date process_time) {
		this.process_time = process_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
