package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * AccountUserThird generated by hbm2java
 */
@Alias("account_user_third")
public class AccountUserThird implements java.io.Serializable {

	private Integer third_user_id;
	private Integer user_id;
	private String user_no;
	private String user_name;
	private Byte account_type;
	private String hear_img;
	private Date create_time;

	public AccountUserThird() {
	}

	public AccountUserThird(Integer third_user_id, Integer user_id, String user_no, String user_name, Byte account_type, String hear_img, Date create_time) {
		this.third_user_id = third_user_id;
		this.user_id = user_id;
		this.user_no = user_no;
		this.user_name = user_name;
		this.account_type = account_type;
		this.hear_img = hear_img;
		this.create_time = create_time;
	}

	public Integer getThird_user_id() {
		return third_user_id;
	}

	public void setThird_user_id(Integer third_user_id) {
		this.third_user_id = third_user_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public String getUser_no() {
		return user_no;
	}

	public void setUser_no(String user_no) {
		this.user_no = user_no;
	}

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	public Byte getAccount_type() {
		return account_type;
	}

	public void setAccount_type(Byte account_type) {
		this.account_type = account_type;
	}

	public String getHear_img() {
		return hear_img;
	}

	public void setHear_img(String hear_img) {
		this.hear_img = hear_img;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
