package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * AccountUserLog generated by hbm2java
 */
@Alias("account_user_log")
public class AccountUserLog implements java.io.Serializable {

	private Integer user_log_id;
	private Integer user_id;
	private String user_name;
	private String ip;
	private Byte user_source;
	private Short status;
	private Integer fail_num;
	private Date create_time;

	public AccountUserLog() {
	}

	public AccountUserLog(Integer user_log_id, Integer user_id, String user_name, String ip, Byte user_source, Short status, Integer fail_num, Date create_time) {
		this.user_log_id = user_log_id;
		this.user_id = user_id;
		this.user_name = user_name;
		this.ip = ip;
		this.user_source = user_source;
		this.status = status;
		this.fail_num = fail_num;
		this.create_time = create_time;
	}

	public Integer getUser_log_id() {
		return user_log_id;
	}

	public void setUser_log_id(Integer user_log_id) {
		this.user_log_id = user_log_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Byte getUser_source() {
		return user_source;
	}

	public void setUser_source(Byte user_source) {
		this.user_source = user_source;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Integer getFail_num() {
		return fail_num;
	}

	public void setFail_num(Integer fail_num) {
		this.fail_num = fail_num;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
