package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import com.hhn.dao.IAccountUserDao;
import com.hhn.util.annotaion.KeyInTable;
import org.apache.ibatis.type.Alias;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * AccountUser generated by hbm2java
 */
@Alias("account_user")
public class AccountUser implements java.io.Serializable {
	@KeyInTable(IAccountUserDao.class)
	private Integer user_id;
	private Byte user_type;
	private String user_name;
	private String password;
	private String real_name;
	private String hear_img;
	private String id_mumber;
	private Byte card_checked;
	private String mobile_phone;
	private Byte phone_checked;
	private String email;
	private Byte email_checked;
	private String validate_code;
	private Character sex;
	private Date birthday;
	private Byte education;
	private String education_no;
	private Byte marriaged;
	private String home_address;
	private Byte industry;
	private Byte scale;
	private Byte income;
	private Byte position;
	private Byte vip_status;
	private Date vip_time;
	private Byte user_source;
	private Byte remind_time_chekced;
	private String base_point;
	private String verify_point;
	private Byte user_status;
	private LoanDetail loanDetail;
	private FundProduct fundProduct;
	private LoanPerson loanPerson;
	private LoanPersonWork loanPersonWork;
	private LoanCompany loanCompany;
	private LoanCorporation loanCorporation;

	@NotNull
	@DateTimeFormat(pattern = "yyyy-mm-dd hh:MM:ss")
	private Date create_time;
	private Date update_time;

	public AccountUser() {
	}

	public AccountUser(Integer user_id, Byte user_type, String user_name, String password, String real_name, String hear_img, String id_mumber, Byte card_checked, String mobile_phone, Byte phone_checked, String email, Byte email_checked, String validate_code, Character sex, Date birthday, Byte education, String education_no, Byte marriaged, String home_address, Byte industry, Byte scale, Byte income, Byte position, Byte vip_status, Date vip_time, Byte user_source, Byte remind_time_chekced, String base_point, String verify_point, Byte user_status, Date create_time, Date update_time) {
		this.user_id = user_id;
		this.user_type = user_type;
		this.user_name = user_name;
		this.password = password;
		this.real_name = real_name;
		this.hear_img = hear_img;
		this.id_mumber = id_mumber;
		this.card_checked = card_checked;
		this.mobile_phone = mobile_phone;
		this.phone_checked = phone_checked;
		this.email = email;
		this.email_checked = email_checked;
		this.validate_code = validate_code;
		this.sex = sex;
		this.birthday = birthday;
		this.education = education;
		this.education_no = education_no;
		this.marriaged = marriaged;
		this.home_address = home_address;
		this.industry = industry;
		this.scale = scale;
		this.income = income;
		this.position = position;
		this.vip_status = vip_status;
		this.vip_time = vip_time;
		this.user_source = user_source;
		this.remind_time_chekced = remind_time_chekced;
		this.base_point = base_point;
		this.verify_point = verify_point;
		this.user_status = user_status;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public Byte getUser_type() {
		return user_type;
	}

	public void setUser_type(Byte user_type) {
		this.user_type = user_type;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getReal_name() {
		return real_name;
	}

	public void setReal_name(String real_name) {
		this.real_name = real_name;
	}

	public String getHear_img() {
		return hear_img;
	}

	public void setHear_img(String hear_img) {
		this.hear_img = hear_img;
	}

	public String getId_mumber() {
		return id_mumber;
	}

	public void setId_mumber(String id_mumber) {
		this.id_mumber = id_mumber;
	}

	public Byte getCard_checked() {
		return card_checked;
	}

	public void setCard_checked(Byte card_checked) {
		this.card_checked = card_checked;
	}

	public String getMobile_phone() {
		return mobile_phone;
	}

	public void setMobile_phone(String mobile_phone) {
		this.mobile_phone = mobile_phone;
	}

	public Byte getPhone_checked() {
		return phone_checked;
	}

	public void setPhone_checked(Byte phone_checked) {
		this.phone_checked = phone_checked;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Byte getEmail_checked() {
		return email_checked;
	}

	public void setEmail_checked(Byte email_checked) {
		this.email_checked = email_checked;
	}

	public String getValidate_code() {
		return validate_code;
	}

	public void setValidate_code(String validate_code) {
		this.validate_code = validate_code;
	}

	public Character getSex() {
		return sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Byte getEducation() {
		return education;
	}

	public void setEducation(Byte education) {
		this.education = education;
	}

	public String getEducation_no() {
		return education_no;
	}

	public void setEducation_no(String education_no) {
		this.education_no = education_no;
	}

	public Byte getMarriaged() {
		return marriaged;
	}

	public void setMarriaged(Byte marriaged) {
		this.marriaged = marriaged;
	}

	public String getHome_address() {
		return home_address;
	}

	public void setHome_address(String home_address) {
		this.home_address = home_address;
	}

	public Byte getIndustry() {
		return industry;
	}

	public void setIndustry(Byte industry) {
		this.industry = industry;
	}

	public Byte getScale() {
		return scale;
	}

	public void setScale(Byte scale) {
		this.scale = scale;
	}

	public Byte getIncome() {
		return income;
	}

	public void setIncome(Byte income) {
		this.income = income;
	}

	public Byte getPosition() {
		return position;
	}

	public void setPosition(Byte position) {
		this.position = position;
	}

	public Byte getVip_status() {
		return vip_status;
	}

	public void setVip_status(Byte vip_status) {
		this.vip_status = vip_status;
	}

	public Date getVip_time() {
		return vip_time;
	}

	public void setVip_time(Date vip_time) {
		this.vip_time = vip_time;
	}

	public Byte getUser_source() {
		return user_source;
	}

	public void setUser_source(Byte user_source) {
		this.user_source = user_source;
	}

	public Byte getRemind_time_chekced() {
		return remind_time_chekced;
	}

	public void setRemind_time_chekced(Byte remind_time_chekced) {
		this.remind_time_chekced = remind_time_chekced;
	}

	public String getBase_point() {
		return base_point;
	}

	public void setBase_point(String base_point) {
		this.base_point = base_point;
	}

	public String getVerify_point() {
		return verify_point;
	}

	public void setVerify_point(String verify_point) {
		this.verify_point = verify_point;
	}

	public Byte getUser_status() {
		return user_status;
	}

	public void setUser_status(Byte user_status) {
		this.user_status = user_status;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public LoanDetail getLoanDetail() {
		return loanDetail;
	}

	public FundProduct getFundProduct() {
		return fundProduct;
	}

	public LoanPerson getLoanPerson() {
		return loanPerson;
	}

	public LoanPersonWork getLoanPersonWork() {
		return loanPersonWork;
	}

	public LoanCompany getLoanCompany() {
		return loanCompany;
	}

	public LoanCorporation getLoanCorporation() {
		return loanCorporation;
	}

	public void setLoanDetail(LoanDetail loanDetail) {
		this.loanDetail = loanDetail;
	}

	public void setFundProduct(FundProduct fundProduct) {
		this.fundProduct = fundProduct;
	}

	public void setLoanPerson(LoanPerson loanPerson) {
		this.loanPerson = loanPerson;
	}

	public void setLoanPersonWork(LoanPersonWork loanPersonWork) {
		this.loanPersonWork = loanPersonWork;
	}

	public void setLoanCompany(LoanCompany loanCompany) {
		this.loanCompany = loanCompany;
	}

	public void setLoanCorporation(LoanCorporation loanCorporation) {
		this.loanCorporation = loanCorporation;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (!(o instanceof AccountUser)) return false;

		AccountUser user = (AccountUser) o;

		if (!id_mumber.equals(user.id_mumber)) return false;
		if (!user_name.equals(user.user_name)) return false;

		return true;
	}

	@Override
	public int hashCode() {
		int result = user_name.hashCode();
		result = 31 * result + id_mumber.hashCode();
		return result;
	}

}
