package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * DicRiskFactor generated by hbm2java
 */
@Alias("dic_risk_factor")
public class DicRiskFactor implements java.io.Serializable {

	private int id;
	@NotNull
	private byte category_type;
	@NotNull
	private byte category;
	private String description;
	@NotNull
	private int item;
	@NotNull
	private int item_key1;
	private Integer item_key2;
	@NotNull
	private int item_value;
	@NotNull
	private Date update_time;

	public DicRiskFactor() {
	}

	public DicRiskFactor(int id, byte category_type, byte category, String description, int item, int item_key1, Integer item_key2, int item_value, Date update_time) {
		this.id = id;
		this.category_type = category_type;
		this.category = category;
		this.description = description;
		this.item = item;
		this.item_key1 = item_key1;
		this.item_key2 = item_key2;
		this.item_value = item_value;
		this.update_time = update_time;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public byte getCategory_type() {
		return category_type;
	}

	public void setCategory_type(byte category_type) {
		this.category_type = category_type;
	}

	public byte getCategory() {
		return category;
	}

	public void setCategory(byte category) {
		this.category = category;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getItem() {
		return item;
	}

	public void setItem(int item) {
		this.item = item;
	}

	public int getItem_key1() {
		return item_key1;
	}

	public void setItem_key1(int item_key1) {
		this.item_key1 = item_key1;
	}

	public Integer getItem_key2() {
		return item_key2;
	}

	public void setItem_key2(Integer item_key2) {
		this.item_key2 = item_key2;
	}

	public int getItem_value() {
		return item_value;
	}

	public void setItem_value(int item_value) {
		this.item_value = item_value;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
