package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * DicRiskCreditGrade generated by hbm2java
 */
@Alias("dic_risk_credit_grade")
public class DicRiskCreditGrade implements java.io.Serializable {

	private int id;
	@NotNull
	private byte borrower_type;
	@NotNull
	private int min;
	@NotNull
	private int max;
	@NotNull
	private String credit_grade;
	@NotNull
	private Date update_time;

	public DicRiskCreditGrade() {
	}

	public DicRiskCreditGrade(int id, byte borrower_type, int min, int max, String credit_grade, Date update_time) {
		this.id = id;
		this.borrower_type = borrower_type;
		this.min = min;
		this.max = max;
		this.credit_grade = credit_grade;
		this.update_time = update_time;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public byte getBorrower_type() {
		return borrower_type;
	}

	public void setBorrower_type(byte borrower_type) {
		this.borrower_type = borrower_type;
	}

	public int getMin() {
		return min;
	}

	public void setMin(int min) {
		this.min = min;
	}

	public int getMax() {
		return max;
	}

	public void setMax(int max) {
		this.max = max;
	}

	public String getCredit_grade() {
		return credit_grade;
	}

	public void setCredit_grade(String credit_grade) {
		this.credit_grade = credit_grade;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
