package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * FundMesageRemindType generated by hbm2java
 */
@Alias("fund_message_remind_type")
public class FundMessageRemindType implements java.io.Serializable {

	private Integer message_remind_type_id;
	private Integer invest_type;
	private String message_name;
	private Integer status;
	private Date create_time;

	public FundMessageRemindType() {
	}

	public FundMessageRemindType(Integer message_remind_type_id, Integer invest_type, String message_name, Integer status, Date create_time) {
		this.message_remind_type_id = message_remind_type_id;
		this.invest_type = invest_type;
		this.message_name = message_name;
		this.status = status;
		this.create_time = create_time;
	}

	public Integer getMessage_remind_type_id() {
		return message_remind_type_id;
	}

	public void setMessage_remind_type_id(Integer message_remind_type_id) {
		this.message_remind_type_id = message_remind_type_id;
	}

	public Integer getInvest_type() {
		return invest_type;
	}

	public void setInvest_type(Integer invest_type) {
		this.invest_type = invest_type;
	}

	public String getMessage_name() {
		return message_name;
	}

	public void setMessage_name(String message_name) {
		this.message_name = message_name;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
