package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * FundBankAccount generated by hbm2java
 */
@Alias("fund_bank_account")
public class FundBankAccount implements java.io.Serializable {

	private int bank_account_id;
	private Integer bank_card_id;
	private BigDecimal balance_amount;
	private BigDecimal freeze_amount;
	private String account_type;
	private Date create_time;
	private Date update_time;

	public FundBankAccount() {
	}

	public FundBankAccount(int bank_account_id, Integer bank_card_id, BigDecimal balance_amount, BigDecimal freeze_amount, String account_type, Date create_time, Date update_time) {
		this.bank_account_id = bank_account_id;
		this.bank_card_id = bank_card_id;
		this.balance_amount = balance_amount;
		this.freeze_amount = freeze_amount;
		this.account_type = account_type;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public int getBank_account_id() {
		return bank_account_id;
	}

	public void setBank_account_id(int bank_account_id) {
		this.bank_account_id = bank_account_id;
	}

	public Integer getBank_card_id() {
		return bank_card_id;
	}

	public void setBank_card_id(Integer bank_card_id) {
		this.bank_card_id = bank_card_id;
	}

	public BigDecimal getBalance_amount() {
		return balance_amount;
	}

	public void setBalance_amount(BigDecimal balance_amount) {
		this.balance_amount = balance_amount;
	}

	public BigDecimal getFreeze_amount() {
		return freeze_amount;
	}

	public void setFreeze_amount(BigDecimal freeze_amount) {
		this.freeze_amount = freeze_amount;
	}

	public String getAccount_type() {
		return account_type;
	}

	public void setAccount_type(String account_type) {
		this.account_type = account_type;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
