package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * FundFeedback generated by hbm2java
 */
@Alias("fund_feedback")
public class FundFeedback implements java.io.Serializable {

	private Integer feed_id;
	private Integer user_id;
	private String content;
	private Date create_date;

	public FundFeedback() {
	}

	public FundFeedback(Date create_date, Integer feed_id, Integer user_id, String content) {
		this.create_date = create_date;
		this.feed_id = feed_id;
		this.user_id = user_id;
		this.content = content;
	}

	public Integer getFeed_id() {
		return feed_id;
	}

	public void setFeed_id(Integer feed_id) {
		this.feed_id = feed_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreate_date() {
		return create_date;
	}

	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}
}
