package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * FundNews generated by hbm2java
 */
@Alias("fund_news")
public class FundNews implements java.io.Serializable {

	private Integer news_id;
	private String title;
	private String content;
	private Short type;
	private Date create_date;
	private String keywords;
	private String description;

	public FundNews() {
	}

	public FundNews(Integer news_id, String title, String content, Short type, Date create_date, String keywords, String description) {
		this.news_id = news_id;
		this.title = title;
		this.content = content;
		this.type = type;
		this.create_date = create_date;
		this.keywords = keywords;
		this.description = description;
	}

	public Integer getNews_id() {
		return news_id;
	}

	public void setNews_id(Integer news_id) {
		this.news_id = news_id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Short getType() {
		return type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Date getCreate_date() {
		return create_date;
	}

	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
