package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * FundUserAccount generated by hbm2java
 */
@Alias("fund_user_account")
public class FundUserAccount implements java.io.Serializable {

	private Integer user_account_id;
	private Integer user_id;
	private BigDecimal balance_amount;
	private BigDecimal freeze_amount;
	private BigDecimal invest_amount;
	private BigDecimal total_invest_amount;
	private BigDecimal loan_amount;
	private BigDecimal total_loan_amount;
	private BigDecimal total_income;
	private BigDecimal total_recharge_amount;
	private BigDecimal total_withdraw_amount;
	private String trade_password;
	private Date update_time;
	private Date create_time;

	public FundUserAccount() {
	}


	public FundUserAccount(Integer user_account_id) {
		this.user_account_id = user_account_id;

	}

	public Integer getUser_account_id() {
		return user_account_id;
	}

	public void setUser_account_id(Integer user_account_id) {
		this.user_account_id = user_account_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public BigDecimal getBalance_amount() {
		return balance_amount;
	}

	public void setBalance_amount(BigDecimal balance_amount) {
		this.balance_amount = balance_amount;
	}

	public BigDecimal getFreeze_amount() {
		return freeze_amount;
	}

	public void setFreeze_amount(BigDecimal freeze_amount) {
		this.freeze_amount = freeze_amount;
	}

	public BigDecimal getInvest_amount() {
		return invest_amount;
	}

	public void setInvest_amount(BigDecimal invest_amount) {
		this.invest_amount = invest_amount;
	}

	public BigDecimal getTotal_invest_amount() {
		return total_invest_amount;
	}

	public void setTotal_invest_amount(BigDecimal total_invest_amount) {
		this.total_invest_amount = total_invest_amount;
	}

	public BigDecimal getLoan_amount() {
		return loan_amount;
	}

	public void setLoan_amount(BigDecimal loan_amount) {
		this.loan_amount = loan_amount;
	}

	public BigDecimal getTotal_loan_amount() {
		return total_loan_amount;
	}

	public void setTotal_loan_amount(BigDecimal total_loan_amount) {
		this.total_loan_amount = total_loan_amount;
	}

	public BigDecimal getTotal_income() {
		return total_income;
	}

	public void setTotal_income(BigDecimal total_income) {
		this.total_income = total_income;
	}

	public BigDecimal getTotal_recharge_amount() {
		return total_recharge_amount;
	}

	public void setTotal_recharge_amount(BigDecimal total_recharge_amount) {
		this.total_recharge_amount = total_recharge_amount;
	}

	public BigDecimal getTotal_withdraw_amount() {
		return total_withdraw_amount;
	}

	public void setTotal_withdraw_amount(BigDecimal total_withdraw_amount) {
		this.total_withdraw_amount = total_withdraw_amount;
	}

	public String getTrade_password() {
		return trade_password;
	}

	public void setTrade_password(String trade_password) {
		this.trade_password = trade_password;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
