package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * FundReceipt generated by hbm2java
 */
@Alias("fund_receipt")
public class FundReceipt implements java.io.Serializable {
	private Integer receipt_id;
	private Integer product_id;
	private Integer trade_id;
	private Integer user_id;
	private BigDecimal principal_amount;
	private BigDecimal interest_amount;
	private BigDecimal penalty_amount;
	private String receipt_type;
	private String receipt_status;
	private Date receipt_date;
	private String remark;
	private Date create_time;
	private Date update_time;

	public FundReceipt() {
	}

	public FundReceipt(Integer receipt_id, Integer product_id, Integer trade_id, Integer user_id, BigDecimal principal_amount, BigDecimal interest_amount, BigDecimal penalty_amount, String receipt_type, String receipt_status, Date receipt_date, String remark, Date create_time, Date update_time) {
		this.receipt_id = receipt_id;
		this.product_id = product_id;
		this.trade_id = trade_id;
		this.user_id = user_id;
		this.principal_amount = principal_amount;
		this.interest_amount = interest_amount;
		this.penalty_amount = penalty_amount;
		this.receipt_type = receipt_type;
		this.receipt_status = receipt_status;
		this.receipt_date = receipt_date;
		this.remark = remark;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public Integer getReceipt_id() {
		return receipt_id;
	}

	public void setReceipt_id(Integer receipt_id) {
		this.receipt_id = receipt_id;
	}

	public Integer getProduct_id() {
		return product_id;
	}

	public void setProduct_id(Integer product_id) {
		this.product_id = product_id;
	}

	public Integer getTrade_id() {
		return trade_id;
	}

	public void setTrade_id(Integer trade_id) {
		this.trade_id = trade_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public BigDecimal getPrincipal_amount() {
		return principal_amount;
	}

	public void setPrincipal_amount(BigDecimal principal_amount) {
		this.principal_amount = principal_amount;
	}

	public BigDecimal getInterest_amount() {
		return interest_amount;
	}

	public void setInterest_amount(BigDecimal interest_amount) {
		this.interest_amount = interest_amount;
	}

	public BigDecimal getPenalty_amount() {
		return penalty_amount;
	}

	public void setPenalty_amount(BigDecimal penalty_amount) {
		this.penalty_amount = penalty_amount;
	}

	public String getReceipt_type() {
		return receipt_type;
	}

	public void setReceipt_type(String receipt_type) {
		this.receipt_type = receipt_type;
	}

	public String getReceipt_status() {
		return receipt_status;
	}

	public void setReceipt_status(String receipt_status) {
		this.receipt_status = receipt_status;
	}

	public Date getReceipt_date() {
		return receipt_date;
	}

	public void setReceipt_date(Date receipt_date) {
		this.receipt_date = receipt_date;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
