package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * FundActualAccountLog generated by hbm2java
 */
@Alias("fund_actual_account_log")
public class FundActualAccountLog implements java.io.Serializable {

	private Integer actual_account_log_id;
	private Integer user_id;
	private BigDecimal trade_amount;
	private String from_account;
	private String to_account;
	private Integer third_pay_type;
	private String third_pay_account_no;
	private String third_pay_id;
	private Date third_trade_time;
	private String remark;
	private String transfer_status;
	private Date update_time;

	public FundActualAccountLog() {
	}

	public FundActualAccountLog(Integer actual_account_log_id) {
		this.actual_account_log_id = actual_account_log_id;

	}

	public Integer getActual_account_log_id() {
		return actual_account_log_id;
	}

	public void setActual_account_log_id(Integer actual_account_log_id) {
		this.actual_account_log_id = actual_account_log_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public BigDecimal getTrade_amount() {
		return trade_amount;
	}

	public void setTrade_amount(BigDecimal trade_amount) {
		this.trade_amount = trade_amount;
	}

	public String getFrom_account() {
		return from_account;
	}

	public void setFrom_account(String from_account) {
		this.from_account = from_account;
	}

	public String getTo_account() {
		return to_account;
	}

	public void setTo_account(String to_account) {
		this.to_account = to_account;
	}

	public Integer getThird_pay_type() {
		return third_pay_type;
	}

	public void setThird_pay_type(Integer third_pay_type) {
		this.third_pay_type = third_pay_type;
	}

	public String getThird_pay_account_no() {
		return third_pay_account_no;
	}

	public void setThird_pay_account_no(String third_pay_account_no) {
		this.third_pay_account_no = third_pay_account_no;
	}

	public String getThird_pay_id() {
		return third_pay_id;
	}

	public void setThird_pay_id(String third_pay_id) {
		this.third_pay_id = third_pay_id;
	}

	public Date getThird_trade_time() {
		return third_trade_time;
	}

	public void setThird_trade_time(Date third_trade_time) {
		this.third_trade_time = third_trade_time;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getTransfer_status() {
		return transfer_status;
	}

	public void setTransfer_status(String transfer_status) {
		this.transfer_status = transfer_status;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
