package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

/**
 * FundFeePayoutLog generated by hbm2java
 */
@Alias("fund_fee_payout_log")
public class FundFeePayoutLog implements java.io.Serializable {

	private Integer fee_id;
	@NotNull
	private int actual_account_log_id;
	@NotNull
	private BigDecimal fee_amount;
	private String remark;
	@NotNull
	private Date create_time;

	public FundFeePayoutLog() {
	}

	public FundFeePayoutLog(int actual_account_log_id, Integer fee_id, BigDecimal fee_amount, String remark, Date create_time) {
		this.actual_account_log_id = actual_account_log_id;
		this.fee_id = fee_id;
		this.fee_amount = fee_amount;
		this.remark = remark;
		this.create_time = create_time;
	}

	public Integer getFee_id() {
		return fee_id;
	}

	public void setFee_id(Integer fee_id) {
		this.fee_id = fee_id;
	}

	public int getActual_account_log_id() {
		return actual_account_log_id;
	}

	public void setActual_account_log_id(int actual_account_log_id) {
		this.actual_account_log_id = actual_account_log_id;
	}

	public BigDecimal getFee_amount() {
		return fee_amount;
	}

	public void setFee_amount(BigDecimal fee_amount) {
		this.fee_amount = fee_amount;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
