package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;

/**
 * FundMessageRecipient generated by hbm2java
 */
@Alias("fund_message_recipient")
public class FundMessageRecipient implements java.io.Serializable {
    @NotNull
    private Integer message_id;

    private Integer recipient_id;
    private Integer is_reader;

    public FundMessageRecipient() {
    }

    public FundMessageRecipient(Integer message_id, Integer recipient_id, Integer is_reader) {
        this.message_id = message_id;
        this.recipient_id = recipient_id;
        this.is_reader = is_reader;
    }

    public Integer getIs_reader() {
        return is_reader;
    }

    public void setIs_reader(Integer is_reader) {
        this.is_reader = is_reader;
    }

    public Integer getMessage_id() {
        return message_id;
    }

    public void setMessage_id(Integer message_id) {
        this.message_id = message_id;
    }

    public Integer getRecipient_id() {
        return recipient_id;
    }

    public void setRecipient_id(Integer recipient_id) {
        this.recipient_id = recipient_id;
    }
}
