package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * FundMessageRemind generated by hbm2java
 */
@Alias("fund_message_remind")
public class FundMessageRemind implements java.io.Serializable {

	private Integer message_remind_id;
	private Integer message_remind_type_id;
	private Integer user_id;
	private Byte message_checked;
	private Byte email_checked;
	private Byte sms_checked;
	private Date create_time;

	public FundMessageRemind() {
	}

	public FundMessageRemind(Integer message_remind_id, Integer message_remind_type_id, Integer user_id, Byte message_checked, Byte email_checked, Byte sms_checked, Date create_time) {
		this.message_remind_id = message_remind_id;
		this.message_remind_type_id = message_remind_type_id;
		this.user_id = user_id;
		this.message_checked = message_checked;
		this.email_checked = email_checked;
		this.sms_checked = sms_checked;
		this.create_time = create_time;
	}

	public Integer getMessage_remind_id() {
		return message_remind_id;
	}

	public void setMessage_remind_id(Integer message_remind_id) {
		this.message_remind_id = message_remind_id;
	}

	public Integer getMessage_remind_type_id() {
		return message_remind_type_id;
	}

	public void setMessage_remind_type_id(Integer message_remind_type_id) {
		this.message_remind_type_id = message_remind_type_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public Byte getMessage_checked() {
		return message_checked;
	}

	public void setMessage_checked(Byte message_checked) {
		this.message_checked = message_checked;
	}

	public Byte getEmail_checked() {
		return email_checked;
	}

	public void setEmail_checked(Byte email_checked) {
		this.email_checked = email_checked;
	}

	public Byte getSms_checked() {
		return sms_checked;
	}

	public void setSms_checked(Byte sms_checked) {
		this.sms_checked = sms_checked;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
