package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

/**
 * FundSubbranchBank generated by hbm2java
 */
@Alias("fund_subbranch_bank")
public class FundSubbranchBank implements java.io.Serializable {

	private Integer subbranch_bank_id;
	private String bank_name;
	private String province;
	private String city;
	private String subbranch_name;

	public FundSubbranchBank() {
	}

	public FundSubbranchBank(Integer subbranch_bank_id, String bank_name, String province, String city, String subbranch_name) {
		this.subbranch_bank_id = subbranch_bank_id;
		this.bank_name = bank_name;
		this.province = province;
		this.city = city;
		this.subbranch_name = subbranch_name;
	}

	public Integer getSubbranch_bank_id() {
		return subbranch_bank_id;
	}

	public void setSubbranch_bank_id(Integer subbranch_bank_id) {
		this.subbranch_bank_id = subbranch_bank_id;
	}

	public String getBank_name() {
		return bank_name;
	}

	public void setBank_name(String bank_name) {
		this.bank_name = bank_name;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getSubbranch_name() {
		return subbranch_name;
	}

	public void setSubbranch_name(String subbranch_name) {
		this.subbranch_name = subbranch_name;
	}
}
