package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * FundBankCard generated by hbm2java
 */
@Alias("fund_bank_card")
public class FundBankCard implements java.io.Serializable {

	private Integer bank_card_id;
	private Integer user_id;
	private String account_name;
	private String bank_name;
	private String province;
	private String city;
	private String detail_address;
	private String card_no;
	private Byte card_type;
	private Byte is_default;
	private Date create_time;
	private Date update_time;

	public FundBankCard() {
	}

	public FundBankCard(Integer bank_card_id) {
		this.bank_card_id = bank_card_id;

	}

	public Integer getBank_card_id() {
		return bank_card_id;
	}

	public void setBank_card_id(Integer bank_card_id) {
		this.bank_card_id = bank_card_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public String getAccount_name() {
		return account_name;
	}

	public void setAccount_name(String account_name) {
		this.account_name = account_name;
	}

	public String getBank_name() {
		return bank_name;
	}

	public void setBank_name(String bank_name) {
		this.bank_name = bank_name;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDetail_address() {
		return detail_address;
	}

	public void setDetail_address(String detail_address) {
		this.detail_address = detail_address;
	}

	public String getCard_no() {
		return card_no;
	}

	public void setCard_no(String card_no) {
		this.card_no = card_no;
	}

	public Byte getCard_type() {
		return card_type;
	}

	public void setCard_type(Byte card_type) {
		this.card_type = card_type;
	}

	public Byte getIs_default() {
		return is_default;
	}

	public void setIs_default(Byte is_default) {
		this.is_default = is_default;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
