package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * FundMessage generated by hbm2java
 */
@Alias("fund_message")
public class FundMessage implements java.io.Serializable {

	private Integer message_id;
	private Integer sender_id;
	private String recipients;
	private Byte message_type;
	private String title;
	private String content;
	private Byte status;
	private Date create_time;

	public FundMessage() {
	}

	public FundMessage(Integer message_id, Integer sender_id, String recipients, Byte message_type, String title, String content, Byte status, Date create_time) {
		this.message_id = message_id;
		this.sender_id = sender_id;
		this.recipients = recipients;
		this.message_type = message_type;
		this.title = title;
		this.content = content;
		this.status = status;
		this.create_time = create_time;
	}

	public Integer getMessage_id() {
		return message_id;
	}

	public void setMessage_id(Integer message_id) {
		this.message_id = message_id;
	}

	public Integer getSender_id() {
		return sender_id;
	}

	public void setSender_id(Integer sender_id) {
		this.sender_id = sender_id;
	}

	public String getRecipients() {
		return recipients;
	}

	public void setRecipients(String recipients) {
		this.recipients = recipients;
	}

	public Byte getMessage_type() {
		return message_type;
	}

	public void setMessage_type(Byte message_type) {
		this.message_type = message_type;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Byte getStatus() {
		return status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
