package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import com.hhn.dao.IFundAccountLogDao;
import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * FundAccountLog generated by hbm2java
 */
@Alias("fund_account_log")
public class FundAccountLog implements java.io.Serializable {

	private Integer account_log_id;
	private Integer trade_id;
	private IFundAccountLogDao.LogType log_type;
	private BigDecimal trade_amount;
	private Integer user_id;
	private Integer user_account_id;
	private String remark;
	private Date trade_time;

	public FundAccountLog() {
	}

	public FundAccountLog(Integer account_log_id) {
		this.account_log_id = account_log_id;

	}

	public Integer getAccount_log_id() {
		return account_log_id;
	}

	public void setAccount_log_id(Integer account_log_id) {
		this.account_log_id = account_log_id;
	}

	public Integer getTrade_id() {
		return trade_id;
	}

	public void setTrade_id(Integer trade_id) {
		this.trade_id = trade_id;
	}

	public IFundAccountLogDao.LogType getLog_type() {
		return log_type;
	}

	public void setLog_type(IFundAccountLogDao.LogType log_type) {
		this.log_type = log_type;
	}

	public BigDecimal getTrade_amount() {
		return trade_amount;
	}

	public void setTrade_amount(BigDecimal trade_amount) {
		this.trade_amount = trade_amount;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public Integer getUser_account_id() {
		return user_account_id;
	}

	public void setUser_account_id(Integer user_account_id) {
		this.user_account_id = user_account_id;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getTrade_time() {
		return trade_time;
	}

	public void setTrade_time(Date trade_time) {
		this.trade_time = trade_time;
	}
}
