package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * FundTrade generated by hbm2java
 */
@Alias("fund_trade")
public class FundTrade implements java.io.Serializable {

	private Integer trade_id;
	private Integer product_id;
	private Integer user_id;
	private Integer user_account_id;
	private volatile BigDecimal trade_amount;
	private volatile BigDecimal trade_balance;
	@NotNull
	private volatile String trade_type;
	@NotNull
	private volatile String trade_status;
	private String remark;
	private Date expect_trade_time;
	private Date trade_time;
	private Date update_time;
	private String target_type;
	private Integer rate_id;
	private List<FundInvestmentDetail> fundInvestmentDetails;
	public FundTrade() {
	}

	public FundTrade(Integer trade_id) {
		this.trade_id = trade_id;

	}

	public List<FundInvestmentDetail> getFundInvestmentDetails() {
		return fundInvestmentDetails;
	}

	public void setFundInvestmentDetails(List<FundInvestmentDetail> fundInvestmentDetails) {
		this.fundInvestmentDetails = fundInvestmentDetails;
	}

	public String getTarget_type() {
		return target_type;
	}

	public void setTarget_type(String target_type) {
		this.target_type = target_type;
	}

	public Integer getTrade_id() {
		return trade_id;
	}

	public void setTrade_id(Integer trade_id) {
		this.trade_id = trade_id;
	}

	public Integer getProduct_id() {
		return product_id;
	}

	public void setProduct_id(Integer product_id) {
		this.product_id = product_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public Integer getUser_account_id() {
		return user_account_id;
	}

	public void setUser_account_id(Integer user_account_id) {
		this.user_account_id = user_account_id;
	}

	public BigDecimal getTrade_amount() {
		return trade_amount;
	}

	public void setTrade_amount(BigDecimal trade_amount) {
		this.trade_amount = trade_amount;
	}

	public BigDecimal getTrade_balance() {
		return trade_balance;
	}

	public void setTrade_balance(BigDecimal trade_balance) {
		this.trade_balance = trade_balance;
	}

	public String getTrade_type() {
		return trade_type;
	}

	public void setTrade_type(String trade_type) {
		this.trade_type = trade_type;
	}

	public String getTrade_status() {
		return trade_status;
	}

	public void setTrade_status(String trade_status) {
		this.trade_status = trade_status;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getExpect_trade_time() {
		return expect_trade_time;
	}

	public void setExpect_trade_time(Date expect_trade_time) {
		this.expect_trade_time = expect_trade_time;
	}

	public Date getTrade_time() {
		return trade_time;
	}

	public void setTrade_time(Date trade_time) {
		this.trade_time = trade_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public Integer getRate_id() {
		return rate_id;
	}

	public void setRate_id(Integer rate_id) {
		this.rate_id = rate_id;
	}
}
