package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * FundRepayment generated by hbm2java
 */
@Alias("fund_repayment")
public class FundRepayment implements java.io.Serializable {

	private Integer repayment_id;
	private Integer trade_id;
	private BigDecimal repay_amount;
	private BigDecimal repaid_amount;
	private BigDecimal penalty_amount;
	private BigDecimal repaid_penalty_amount;
	private String remark;
	private Date create_time;
	private Date update_time;

	public FundRepayment() {
	}

	public FundRepayment(Integer repayment_id, Integer trade_id, BigDecimal repay_amount, BigDecimal repaid_amount, BigDecimal penalty_amount, BigDecimal repaid_penalty_amount, String remark, Date create_time, Date update_time) {
		this.repayment_id = repayment_id;
		this.trade_id = trade_id;
		this.repay_amount = repay_amount;
		this.repaid_amount = repaid_amount;
		this.penalty_amount = penalty_amount;
		this.repaid_penalty_amount = repaid_penalty_amount;
		this.remark = remark;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public Integer getRepayment_id() {
		return repayment_id;
	}

	public void setRepayment_id(Integer repayment_id) {
		this.repayment_id = repayment_id;
	}

	public Integer getTrade_id() {
		return trade_id;
	}

	public void setTrade_id(Integer trade_id) {
		this.trade_id = trade_id;
	}

	public BigDecimal getRepay_amount() {
		return repay_amount;
	}

	public void setRepay_amount(BigDecimal repay_amount) {
		this.repay_amount = repay_amount;
	}

	public BigDecimal getRepaid_amount() {
		return repaid_amount;
	}

	public void setRepaid_amount(BigDecimal repaid_amount) {
		this.repaid_amount = repaid_amount;
	}

	public BigDecimal getPenalty_amount() {
		return penalty_amount;
	}

	public void setPenalty_amount(BigDecimal penalty_amount) {
		this.penalty_amount = penalty_amount;
	}

	public BigDecimal getRepaid_penalty_amount() {
		return repaid_penalty_amount;
	}

	public void setRepaid_penalty_amount(BigDecimal repaid_penalty_amount) {
		this.repaid_penalty_amount = repaid_penalty_amount;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
