package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

/**
 * FundTradeDetail generated by hbm2java
 */
@Alias("fund_trade_detail")
public class FundTradeDetail implements java.io.Serializable {

	private Integer trade_detail_id;
	private Integer trade_id;
	private BigDecimal trade_amount;
	@NotNull
	private String trade_type;
	private Date update_time;

	public FundTradeDetail() {
	}

	public FundTradeDetail(Integer trade_detail_id, Integer trade_id, BigDecimal trade_amount, String trade_type, Date update_time) {
		this.trade_detail_id = trade_detail_id;
		this.trade_id = trade_id;
		this.trade_amount = trade_amount;
		this.trade_type = trade_type;
		this.update_time = update_time;
	}

	public Integer getTrade_detail_id() {
		return trade_detail_id;
	}

	public void setTrade_detail_id(Integer trade_detail_id) {
		this.trade_detail_id = trade_detail_id;
	}

	public Integer getTrade_id() {
		return trade_id;
	}

	public void setTrade_id(Integer trade_id) {
		this.trade_id = trade_id;
	}

	public BigDecimal getTrade_amount() {
		return trade_amount;
	}

	public void setTrade_amount(BigDecimal trade_amount) {
		this.trade_amount = trade_amount;
	}

	public String getTrade_type() {
		return trade_type;
	}

	public void setTrade_type(String trade_type) {
		this.trade_type = trade_type;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
