package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * FundPreRepayment generated by hbm2java
 */
@Alias("fund_pre_repayment")
public class FundPreRepayment implements java.io.Serializable {

	private Integer repayment_id;
	private Integer loan_id;
	private Integer user_id;
	private BigDecimal repay_amount;
	private String repay_status;
	private String repay_type;
	private String remark;
	private Date repay_date;
	private Date create_time;
	private Date update_time;
	private Integer repay_times;
	private BigDecimal pre_repay_amount;
	private Date pre_repay_date;
	private BigDecimal capital;
	private BigDecimal interest;
	private BigDecimal pre_capital;
	private BigDecimal pre_interest;
	private BigDecimal fee_amount;
	private Integer receive_user_id;

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	private String comment;

	public FundPreRepayment() {
	}

	public FundPreRepayment(Integer repayment_id) {
		this.repayment_id = repayment_id;

	}

	public Integer getReceive_user_id() {
		return receive_user_id;
	}

	public void setReceive_user_id(Integer receive_user_id) {
		this.receive_user_id = receive_user_id;
	}

	public String getRepay_type() {
		return repay_type;
	}

	public void setRepay_type(String repay_type) {
		this.repay_type = repay_type;
	}

	public Integer getRepayment_id() {
		return repayment_id;
	}

	public void setRepayment_id(Integer repayment_id) {
		this.repayment_id = repayment_id;
	}

	public Integer getLoan_id() {
		return loan_id;
	}

	public void setLoan_id(Integer loan_id) {
		this.loan_id = loan_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public BigDecimal getRepay_amount() {
		return repay_amount;
	}

	public void setRepay_amount(BigDecimal repay_amount) {
		this.repay_amount = repay_amount;
	}

	public String getRepay_status() {
		return repay_status;
	}

	public void setRepay_status(String repay_status) {
		this.repay_status = repay_status;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getRepay_date() {
		return repay_date;
	}

	public void setRepay_date(Date repay_date) {
		this.repay_date = repay_date;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public Integer getRepay_times() {
		return repay_times;
	}

	public void setRepay_times(Integer repay_times) {
		this.repay_times = repay_times;
	}

	public BigDecimal getPre_repay_amount() {
		return pre_repay_amount;
	}

	public void setPre_repay_amount(BigDecimal pre_repay_amount) {
		this.pre_repay_amount = pre_repay_amount;
	}

	public Date getPre_repay_date() {
		return pre_repay_date;
	}

	public void setPre_repay_date(Date pre_repay_date) {
		this.pre_repay_date = pre_repay_date;
	}

	public BigDecimal getCapital() {
		return capital;
	}

	public void setCapital(BigDecimal capital) {
		this.capital = capital;
	}

	public BigDecimal getInterest() {
		return interest;
	}

	public void setInterest(BigDecimal interest) {
		this.interest = interest;
	}

	public BigDecimal getPre_capital() {
		return pre_capital;
	}

	public void setPre_capital(BigDecimal pre_capital) {
		this.pre_capital = pre_capital;
	}

	public BigDecimal getPre_interest() {
		return pre_interest;
	}

	public void setPre_interest(BigDecimal pre_interest) {
		this.pre_interest = pre_interest;
	}

	public BigDecimal getFee_amount() {
		return fee_amount;
	}

	public void setFee_amount(BigDecimal fee_amount) {
		this.fee_amount = fee_amount;
	}
}
