package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * FundQuestion generated by hbm2java
 */
@Alias("fund_question")
public class FundQuestion implements java.io.Serializable {

	private Integer question_id;
	private Integer parent_question_id;
	private Integer subject_id;
	private Integer user_id;
	private String content;
	private Date create_time;
	private Date update_time;

	public FundQuestion() {
	}

	public FundQuestion(Integer question_id, Integer parent_question_id, Integer subject_id, Integer user_id, String content, Date create_time, Date update_time) {
		this.question_id = question_id;
		this.parent_question_id = parent_question_id;
		this.subject_id = subject_id;
		this.user_id = user_id;
		this.content = content;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public Integer getQuestion_id() {
		return question_id;
	}

	public void setQuestion_id(Integer question_id) {
		this.question_id = question_id;
	}

	public Integer getParent_question_id() {
		return parent_question_id;
	}

	public void setParent_question_id(Integer parent_question_id) {
		this.parent_question_id = parent_question_id;
	}

	public Integer getSubject_id() {
		return subject_id;
	}

	public void setSubject_id(Integer subject_id) {
		this.subject_id = subject_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
