package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanCollateral generated by hbm2java
 */
@Alias("loan_collateral")
public class LoanCollateral implements java.io.Serializable {

	private Integer collateral_id;
	@NotNull
	private int user_id;
	@NotNull
	private String collateral_type;
	private Date purchase_date;
	private BigDecimal purchase_price;
	private Integer use_year;
	private String remark;
	private Date create_time;
	private Date update_time;

	public LoanCollateral() {
	}

	public LoanCollateral(Integer collateral_id, int user_id, String collateral_type, Date purchase_date, BigDecimal purchase_price, Integer use_year, String remark, Date create_time, Date update_time) {
		this.collateral_id = collateral_id;
		this.user_id = user_id;
		this.collateral_type = collateral_type;
		this.purchase_date = purchase_date;
		this.purchase_price = purchase_price;
		this.use_year = use_year;
		this.remark = remark;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public Integer getCollateral_id() {
		return collateral_id;
	}

	public void setCollateral_id(Integer collateral_id) {
		this.collateral_id = collateral_id;
	}

	public int getUser_id() {
		return user_id;
	}

	public void setUser_id(int user_id) {
		this.user_id = user_id;
	}

	public String getCollateral_type() {
		return collateral_type;
	}

	public void setCollateral_type(String collateral_type) {
		this.collateral_type = collateral_type;
	}

	public Date getPurchase_date() {
		return purchase_date;
	}

	public void setPurchase_date(Date purchase_date) {
		this.purchase_date = purchase_date;
	}

	public BigDecimal getPurchase_price() {
		return purchase_price;
	}

	public void setPurchase_price(BigDecimal purchase_price) {
		this.purchase_price = purchase_price;
	}

	public Integer getUse_year() {
		return use_year;
	}

	public void setUse_year(Integer use_year) {
		this.use_year = use_year;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
