package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * LoanCollateralVerify generated by hbm2java
 */
@Alias("loan_collateral_verify")
public class LoanCollateralVerify implements java.io.Serializable {

	private int collateralId;
	private Integer firstWorkerId;
	private Integer firstVerifyStatus;
	private String firstRemark;
	private Date firstVerifyTime;
	private Integer secondWorkerId;
	private Integer secondVerifyStatus;
	private String secondRemark;
	private Date secondVerifyTime;
	private Date createTime;
	private String emailContent;

	public LoanCollateralVerify() {
	}

	public LoanCollateralVerify(int collateralId) {
		this.collateralId = collateralId;
	}

	public LoanCollateralVerify(int collateralId, Integer firstWorkerId,
			Integer firstVerifyStatus, String firstRemark,
			Date firstVerifyTime, Integer secondWorkerId,
			Integer secondVerifyStatus, String secondRemark,
			Date secondVerifyTime, Date createTime, String emailContent) {
		this.collateralId = collateralId;
		this.firstWorkerId = firstWorkerId;
		this.firstVerifyStatus = firstVerifyStatus;
		this.firstRemark = firstRemark;
		this.firstVerifyTime = firstVerifyTime;
		this.secondWorkerId = secondWorkerId;
		this.secondVerifyStatus = secondVerifyStatus;
		this.secondRemark = secondRemark;
		this.secondVerifyTime = secondVerifyTime;
		this.createTime = createTime;
		this.emailContent = emailContent;
	}

	public int getCollateralId() {
		return this.collateralId;
	}

	public void setCollateralId(int collateralId) {
		this.collateralId = collateralId;
	}

	public Integer getFirstWorkerId() {
		return this.firstWorkerId;
	}

	public void setFirstWorkerId(Integer firstWorkerId) {
		this.firstWorkerId = firstWorkerId;
	}

	public Integer getFirstVerifyStatus() {
		return this.firstVerifyStatus;
	}

	public void setFirstVerifyStatus(Integer firstVerifyStatus) {
		this.firstVerifyStatus = firstVerifyStatus;
	}

	public String getFirstRemark() {
		return this.firstRemark;
	}

	public void setFirstRemark(String firstRemark) {
		this.firstRemark = firstRemark;
	}

	public Date getFirstVerifyTime() {
		return this.firstVerifyTime;
	}

	public void setFirstVerifyTime(Date firstVerifyTime) {
		this.firstVerifyTime = firstVerifyTime;
	}

	public Integer getSecondWorkerId() {
		return this.secondWorkerId;
	}

	public void setSecondWorkerId(Integer secondWorkerId) {
		this.secondWorkerId = secondWorkerId;
	}

	public Integer getSecondVerifyStatus() {
		return this.secondVerifyStatus;
	}

	public void setSecondVerifyStatus(Integer secondVerifyStatus) {
		this.secondVerifyStatus = secondVerifyStatus;
	}

	public String getSecondRemark() {
		return this.secondRemark;
	}

	public void setSecondRemark(String secondRemark) {
		this.secondRemark = secondRemark;
	}

	public Date getSecondVerifyTime() {
		return this.secondVerifyTime;
	}

	public void setSecondVerifyTime(Date secondVerifyTime) {
		this.secondVerifyTime = secondVerifyTime;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getEmailContent() {
		return this.emailContent;
	}

	public void setEmailContent(String emailContent) {
		this.emailContent = emailContent;
	}

}
