package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanCollateralReal generated by hbm2java
 */
@Alias("loan_collateral_real")
public class LoanCollateralReal implements java.io.Serializable {

	private Integer collateralId;
	private int loanId;
	private String collateralType;
	private Date purchaseDate;
	private BigDecimal purchasePrice;
	private Integer useYear;
	private String remark;
	private Date createTime;
	private Date updateTime;
	private Integer collateralOldId;
	private Integer userId;
	private String binLevel;

	public LoanCollateralReal() {
	}

	public LoanCollateralReal(int loanId, String collateralType) {
		this.loanId = loanId;
		this.collateralType = collateralType;
	}

	public LoanCollateralReal(int loanId, String collateralType,
			Date purchaseDate, BigDecimal purchasePrice, Integer useYear,
			String remark, Date createTime, Date updateTime,
			Integer collateralOldId, Integer userId, String binLevel) {
		this.loanId = loanId;
		this.collateralType = collateralType;
		this.purchaseDate = purchaseDate;
		this.purchasePrice = purchasePrice;
		this.useYear = useYear;
		this.remark = remark;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.collateralOldId = collateralOldId;
		this.userId = userId;
		this.binLevel = binLevel;
	}

	public Integer getCollateralId() {
		return this.collateralId;
	}

	public void setCollateralId(Integer collateralId) {
		this.collateralId = collateralId;
	}

	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	public String getCollateralType() {
		return this.collateralType;
	}

	public void setCollateralType(String collateralType) {
		this.collateralType = collateralType;
	}

	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public BigDecimal getPurchasePrice() {
		return this.purchasePrice;
	}

	public void setPurchasePrice(BigDecimal purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	public Integer getUseYear() {
		return this.useYear;
	}

	public void setUseYear(Integer useYear) {
		this.useYear = useYear;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getCollateralOldId() {
		return this.collateralOldId;
	}

	public void setCollateralOldId(Integer collateralOldId) {
		this.collateralOldId = collateralOldId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getBinLevel() {
		return this.binLevel;
	}

	public void setBinLevel(String binLevel) {
		this.binLevel = binLevel;
	}

}
