package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * LoanCertificateType generated by hbm2java
 */
@Alias("loan_certificate_type")
public class LoanCertificateType implements java.io.Serializable {

	private int certificate_type_id;
	private Byte borrower_type;
	private String type_name;
	private Byte type_status;
	private Byte required;
	private Short effective_period;
	private String create_user;
	private Date create_time;
	private String update_user;
	private Date update_time;

	public LoanCertificateType() {
	}

	public LoanCertificateType(int certificate_type_id, Byte borrower_type, String type_name, Byte type_status, Byte required, Short effective_period, String create_user, Date create_time, String update_user, Date update_time) {
		this.certificate_type_id = certificate_type_id;
		this.borrower_type = borrower_type;
		this.type_name = type_name;
		this.type_status = type_status;
		this.required = required;
		this.effective_period = effective_period;
		this.create_user = create_user;
		this.create_time = create_time;
		this.update_user = update_user;
		this.update_time = update_time;
	}

	public int getCertificate_type_id() {
		return certificate_type_id;
	}

	public void setCertificate_type_id(int certificate_type_id) {
		this.certificate_type_id = certificate_type_id;
	}

	public Byte getBorrower_type() {
		return borrower_type;
	}

	public void setBorrower_type(Byte borrower_type) {
		this.borrower_type = borrower_type;
	}

	public String getType_name() {
		return type_name;
	}

	public void setType_name(String type_name) {
		this.type_name = type_name;
	}

	public Byte getType_status() {
		return type_status;
	}

	public void setType_status(Byte type_status) {
		this.type_status = type_status;
	}

	public Byte getRequired() {
		return required;
	}

	public void setRequired(Byte required) {
		this.required = required;
	}

	public Short getEffective_period() {
		return effective_period;
	}

	public void setEffective_period(Short effective_period) {
		this.effective_period = effective_period;
	}

	public String getCreate_user() {
		return create_user;
	}

	public void setCreate_user(String create_user) {
		this.create_user = create_user;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public String getUpdate_user() {
		return update_user;
	}

	public void setUpdate_user(String update_user) {
		this.update_user = update_user;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
