package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

/**
 * LoanCertificateAudi generated by hbm2java
 */
@Alias("loan_certificate_audi")
public class LoanCertificateAudi implements java.io.Serializable {

	private Integer loan_certificate_audi_id;
	private Integer loan_id;
	private Short verify_stage;
	private Integer certificate_type_id;
	private Double first_verify_point;
	private String first_fail_content;
	private String first_remark;
	private Short first_result;
	private Short first_status;
	private Double second_verify_point;
	private String second_fail_content;
	private String second_remark;
	private Short second_result;
	private Short second_status;

	public LoanCertificateAudi() {
	}

	public LoanCertificateAudi(Integer loan_certificate_audi_id, Integer loan_id, Short verify_stage, Integer certificate_type_id, Double first_verify_point, String first_fail_content, String first_remark, Short first_result, Short first_status, Double second_verify_point, String second_fail_content, String second_remark, Short second_result, Short second_status) {
		this.loan_certificate_audi_id = loan_certificate_audi_id;
		this.loan_id = loan_id;
		this.verify_stage = verify_stage;
		this.certificate_type_id = certificate_type_id;
		this.first_verify_point = first_verify_point;
		this.first_fail_content = first_fail_content;
		this.first_remark = first_remark;
		this.first_result = first_result;
		this.first_status = first_status;
		this.second_verify_point = second_verify_point;
		this.second_fail_content = second_fail_content;
		this.second_remark = second_remark;
		this.second_result = second_result;
		this.second_status = second_status;
	}

	public Integer getLoan_certificate_audi_id() {
		return loan_certificate_audi_id;
	}

	public void setLoan_certificate_audi_id(Integer loan_certificate_audi_id) {
		this.loan_certificate_audi_id = loan_certificate_audi_id;
	}

	public Integer getLoan_id() {
		return loan_id;
	}

	public void setLoan_id(Integer loan_id) {
		this.loan_id = loan_id;
	}

	public Short getVerify_stage() {
		return verify_stage;
	}

	public void setVerify_stage(Short verify_stage) {
		this.verify_stage = verify_stage;
	}

	public Integer getCertificate_type_id() {
		return certificate_type_id;
	}

	public void setCertificate_type_id(Integer certificate_type_id) {
		this.certificate_type_id = certificate_type_id;
	}

	public Double getFirst_verify_point() {
		return first_verify_point;
	}

	public void setFirst_verify_point(Double first_verify_point) {
		this.first_verify_point = first_verify_point;
	}

	public String getFirst_fail_content() {
		return first_fail_content;
	}

	public void setFirst_fail_content(String first_fail_content) {
		this.first_fail_content = first_fail_content;
	}

	public String getFirst_remark() {
		return first_remark;
	}

	public void setFirst_remark(String first_remark) {
		this.first_remark = first_remark;
	}

	public Short getFirst_result() {
		return first_result;
	}

	public void setFirst_result(Short first_result) {
		this.first_result = first_result;
	}

	public Short getFirst_status() {
		return first_status;
	}

	public void setFirst_status(Short first_status) {
		this.first_status = first_status;
	}

	public Double getSecond_verify_point() {
		return second_verify_point;
	}

	public void setSecond_verify_point(Double second_verify_point) {
		this.second_verify_point = second_verify_point;
	}

	public String getSecond_fail_content() {
		return second_fail_content;
	}

	public void setSecond_fail_content(String second_fail_content) {
		this.second_fail_content = second_fail_content;
	}

	public String getSecond_remark() {
		return second_remark;
	}

	public void setSecond_remark(String second_remark) {
		this.second_remark = second_remark;
	}

	public Short getSecond_result() {
		return second_result;
	}

	public void setSecond_result(Short second_result) {
		this.second_result = second_result;
	}

	public Short getSecond_status() {
		return second_status;
	}

	public void setSecond_status(Short second_status) {
		this.second_status = second_status;
	}
}
