package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanVerify generated by hbm2java
 */
@Alias("loan_verify")
public class LoanVerify implements java.io.Serializable {

	private int loanId;
	private Integer firstWorkerId;
	private Integer secondWorkerId;
	private Integer thirdWorkerId;
	private Integer firstVerifyStatus;
	private String firstRemark;
	private Double totalFirstPoint;
	private Double totalSecondPint;
	private String secondRemark;
	private String thirdRemark;
	private Double loanAmount;
	private Integer loanDeadline;
	private BigDecimal yearRate;
	private Integer rmbCollectDay;
	private Date createTime;
	private Date firstVerifyTime;
	private Date secondVerifyTime;
	private Date thirdVerifyTime;
	private String emailContent;
	private Integer secondVerifyStatus;
	private Integer thirdVerifyStatus;
	private String verifySuggest;

	public LoanVerify() {
	}

	public LoanVerify(int loanId) {
		this.loanId = loanId;
	}

	public LoanVerify(int loanId, Integer firstWorkerId,
			Integer secondWorkerId, Integer thirdWorkerId,
			Integer firstVerifyStatus, String firstRemark,
			Double totalFirstPoint, Double totalSecondPint,
			String secondRemark, String thirdRemark, Double loanAmount,
			Integer loanDeadline, BigDecimal yearRate, Integer rmbCollectDay,
			Date createTime, Date firstVerifyTime, Date secondVerifyTime,
			Date thirdVerifyTime, String emailContent,
			Integer secondVerifyStatus, Integer thirdVerifyStatus,
			String verifySuggest) {
		this.loanId = loanId;
		this.firstWorkerId = firstWorkerId;
		this.secondWorkerId = secondWorkerId;
		this.thirdWorkerId = thirdWorkerId;
		this.firstVerifyStatus = firstVerifyStatus;
		this.firstRemark = firstRemark;
		this.totalFirstPoint = totalFirstPoint;
		this.totalSecondPint = totalSecondPint;
		this.secondRemark = secondRemark;
		this.thirdRemark = thirdRemark;
		this.loanAmount = loanAmount;
		this.loanDeadline = loanDeadline;
		this.yearRate = yearRate;
		this.rmbCollectDay = rmbCollectDay;
		this.createTime = createTime;
		this.firstVerifyTime = firstVerifyTime;
		this.secondVerifyTime = secondVerifyTime;
		this.thirdVerifyTime = thirdVerifyTime;
		this.emailContent = emailContent;
		this.secondVerifyStatus = secondVerifyStatus;
		this.thirdVerifyStatus = thirdVerifyStatus;
		this.verifySuggest = verifySuggest;
	}

	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	public Integer getFirstWorkerId() {
		return this.firstWorkerId;
	}

	public void setFirstWorkerId(Integer firstWorkerId) {
		this.firstWorkerId = firstWorkerId;
	}

	public Integer getSecondWorkerId() {
		return this.secondWorkerId;
	}

	public void setSecondWorkerId(Integer secondWorkerId) {
		this.secondWorkerId = secondWorkerId;
	}

	public Integer getThirdWorkerId() {
		return this.thirdWorkerId;
	}

	public void setThirdWorkerId(Integer thirdWorkerId) {
		this.thirdWorkerId = thirdWorkerId;
	}

	public Integer getFirstVerifyStatus() {
		return this.firstVerifyStatus;
	}

	public void setFirstVerifyStatus(Integer firstVerifyStatus) {
		this.firstVerifyStatus = firstVerifyStatus;
	}

	public String getFirstRemark() {
		return this.firstRemark;
	}

	public void setFirstRemark(String firstRemark) {
		this.firstRemark = firstRemark;
	}

	public Double getTotalFirstPoint() {
		return this.totalFirstPoint;
	}

	public void setTotalFirstPoint(Double totalFirstPoint) {
		this.totalFirstPoint = totalFirstPoint;
	}

	public Double getTotalSecondPint() {
		return this.totalSecondPint;
	}

	public void setTotalSecondPint(Double totalSecondPint) {
		this.totalSecondPint = totalSecondPint;
	}

	public String getSecondRemark() {
		return this.secondRemark;
	}

	public void setSecondRemark(String secondRemark) {
		this.secondRemark = secondRemark;
	}

	public String getThirdRemark() {
		return this.thirdRemark;
	}

	public void setThirdRemark(String thirdRemark) {
		this.thirdRemark = thirdRemark;
	}

	public Double getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(Double loanAmount) {
		this.loanAmount = loanAmount;
	}

	public Integer getLoanDeadline() {
		return this.loanDeadline;
	}

	public void setLoanDeadline(Integer loanDeadline) {
		this.loanDeadline = loanDeadline;
	}

	public BigDecimal getYearRate() {
		return this.yearRate;
	}

	public void setYearRate(BigDecimal yearRate) {
		this.yearRate = yearRate;
	}

	public Integer getRmbCollectDay() {
		return this.rmbCollectDay;
	}

	public void setRmbCollectDay(Integer rmbCollectDay) {
		this.rmbCollectDay = rmbCollectDay;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getFirstVerifyTime() {
		return this.firstVerifyTime;
	}

	public void setFirstVerifyTime(Date firstVerifyTime) {
		this.firstVerifyTime = firstVerifyTime;
	}

	public Date getSecondVerifyTime() {
		return this.secondVerifyTime;
	}

	public void setSecondVerifyTime(Date secondVerifyTime) {
		this.secondVerifyTime = secondVerifyTime;
	}

	public Date getThirdVerifyTime() {
		return this.thirdVerifyTime;
	}

	public void setThirdVerifyTime(Date thirdVerifyTime) {
		this.thirdVerifyTime = thirdVerifyTime;
	}

	public String getEmailContent() {
		return this.emailContent;
	}

	public void setEmailContent(String emailContent) {
		this.emailContent = emailContent;
	}

	public Integer getSecondVerifyStatus() {
		return this.secondVerifyStatus;
	}

	public void setSecondVerifyStatus(Integer secondVerifyStatus) {
		this.secondVerifyStatus = secondVerifyStatus;
	}

	public Integer getThirdVerifyStatus() {
		return this.thirdVerifyStatus;
	}

	public void setThirdVerifyStatus(Integer thirdVerifyStatus) {
		this.thirdVerifyStatus = thirdVerifyStatus;
	}

	public String getVerifySuggest() {
		return this.verifySuggest;
	}

	public void setVerifySuggest(String verifySuggest) {
		this.verifySuggest = verifySuggest;
	}

}
