package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * LoanPersonWork generated by hbm2java
 */
@Alias("loan_person_work")
public class LoanPersonWork implements java.io.Serializable {

	private Integer person_work_id;
	private Integer loan_person_id;
	@NotNull(message = "请登录后再操作")
//	@KeyInTable(value = IAccountUserDao.class,message = "无此用户....")
	private Integer user_id;
	private Integer loan_id;
	private String com_full_name;
	private String department;
	private Byte position;
	private Byte income;
	private String email;
	private Integer working_address_id;
	private Byte com_type;
	private Byte industry;
	private Byte scale;
	private Short work_year;
	private String com_telephone;
	private Date create_time;
	private Date update_time;

	public LoanPersonWork() {
	}

	public LoanPersonWork(Integer person_work_id, Integer loan_person_id, Integer user_id, Integer loan_id, String com_full_name, String department, Byte position, Byte income, String email, Integer working_address_id, Byte com_type, Byte industry, Byte scale, Short work_year, String com_telephone, Date create_time, Date update_time) {
		this.person_work_id = person_work_id;
		this.loan_person_id = loan_person_id;
		this.user_id = user_id;
		this.loan_id = loan_id;
		this.com_full_name = com_full_name;
		this.department = department;
		this.position = position;
		this.income = income;
		this.email = email;
		this.working_address_id = working_address_id;
		this.com_type = com_type;
		this.industry = industry;
		this.scale = scale;
		this.work_year = work_year;
		this.com_telephone = com_telephone;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public Integer getPerson_work_id() {
		return person_work_id;
	}

	public void setPerson_work_id(Integer person_work_id) {
		this.person_work_id = person_work_id;
	}

	public Integer getLoan_person_id() {
		return loan_person_id;
	}

	public void setLoan_person_id(Integer loan_person_id) {
		this.loan_person_id = loan_person_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public Integer getLoan_id() {
		return loan_id;
	}

	public void setLoan_id(Integer loan_id) {
		this.loan_id = loan_id;
	}

	public String getCom_full_name() {
		return com_full_name;
	}

	public void setCom_full_name(String com_full_name) {
		this.com_full_name = com_full_name;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public Byte getPosition() {
		return position;
	}

	public void setPosition(Byte position) {
		this.position = position;
	}

	public Byte getIncome() {
		return income;
	}

	public void setIncome(Byte income) {
		this.income = income;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getWorking_address_id() {
		return working_address_id;
	}

	public void setWorking_address_id(Integer working_address_id) {
		this.working_address_id = working_address_id;
	}

	public Byte getCom_type() {
		return com_type;
	}

	public void setCom_type(Byte com_type) {
		this.com_type = com_type;
	}

	public Byte getIndustry() {
		return industry;
	}

	public void setIndustry(Byte industry) {
		this.industry = industry;
	}

	public Byte getScale() {
		return scale;
	}

	public void setScale(Byte scale) {
		this.scale = scale;
	}

	public Short getWork_year() {
		return work_year;
	}

	public void setWork_year(Short work_year) {
		this.work_year = work_year;
	}

	public String getCom_telephone() {
		return com_telephone;
	}

	public void setCom_telephone(String com_telephone) {
		this.com_telephone = com_telephone;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
