package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * LoanCertificate generated by hbm2java
 */
@Alias("loan_certificate")
public class LoanCertificate implements java.io.Serializable {

	private Integer certificate_id;
	private Integer loan_id;
	private Integer certificate_type_id;
	private Integer borrower_id;
	private Byte borrower_type;
	private String file_path;
	private Byte file_type;
	private String reject_content;
	private Byte certificat_status;
	private String qq_number;
	private String weixin_number;
	private String weibo_number;
	private Date create_time;
	private Date expire_date;
	private Date delete_time;
	private Byte is_examine;

	public LoanCertificate() {
	}

	public LoanCertificate(Integer certificate_id, Integer loan_id, Integer certificate_type_id, Integer borrower_id, Byte borrower_type, String file_path, Byte file_type, String reject_content, Byte certificat_status, String qq_number, String weixin_number, String weibo_number, Date create_time, Date expire_date, Date delete_time, Byte is_examine) {
		this.certificate_id = certificate_id;
		this.loan_id = loan_id;
		this.certificate_type_id = certificate_type_id;
		this.borrower_id = borrower_id;
		this.borrower_type = borrower_type;
		this.file_path = file_path;
		this.file_type = file_type;
		this.reject_content = reject_content;
		this.certificat_status = certificat_status;
		this.qq_number = qq_number;
		this.weixin_number = weixin_number;
		this.weibo_number = weibo_number;
		this.create_time = create_time;
		this.expire_date = expire_date;
		this.delete_time = delete_time;
		this.is_examine = is_examine;
	}

	public Integer getCertificate_id() {
		return certificate_id;
	}

	public void setCertificate_id(Integer certificate_id) {
		this.certificate_id = certificate_id;
	}

	public Integer getLoan_id() {
		return loan_id;
	}

	public void setLoan_id(Integer loan_id) {
		this.loan_id = loan_id;
	}

	public Integer getCertificate_type_id() {
		return certificate_type_id;
	}

	public void setCertificate_type_id(Integer certificate_type_id) {
		this.certificate_type_id = certificate_type_id;
	}

	public Integer getBorrower_id() {
		return borrower_id;
	}

	public void setBorrower_id(Integer borrower_id) {
		this.borrower_id = borrower_id;
	}

	public Byte getBorrower_type() {
		return borrower_type;
	}

	public void setBorrower_type(Byte borrower_type) {
		this.borrower_type = borrower_type;
	}

	public String getFile_path() {
		return file_path;
	}

	public void setFile_path(String file_path) {
		this.file_path = file_path;
	}

	public Byte getFile_type() {
		return file_type;
	}

	public void setFile_type(Byte file_type) {
		this.file_type = file_type;
	}

	public String getReject_content() {
		return reject_content;
	}

	public void setReject_content(String reject_content) {
		this.reject_content = reject_content;
	}

	public Byte getCertificat_status() {
		return certificat_status;
	}

	public void setCertificat_status(Byte certificat_status) {
		this.certificat_status = certificat_status;
	}

	public String getQq_number() {
		return qq_number;
	}

	public void setQq_number(String qq_number) {
		this.qq_number = qq_number;
	}

	public String getWeixin_number() {
		return weixin_number;
	}

	public void setWeixin_number(String weixin_number) {
		this.weixin_number = weixin_number;
	}

	public String getWeibo_number() {
		return weibo_number;
	}

	public void setWeibo_number(String weibo_number) {
		this.weibo_number = weibo_number;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getExpire_date() {
		return expire_date;
	}

	public void setExpire_date(Date expire_date) {
		this.expire_date = expire_date;
	}

	public Date getDelete_time() {
		return delete_time;
	}

	public void setDelete_time(Date delete_time) {
		this.delete_time = delete_time;
	}

	public Byte getIs_examine() {
		return is_examine;
	}

	public void setIs_examine(Byte is_examine) {
		this.is_examine = is_examine;
	}
}
