package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

/**
 * LoanAddress generated by hbm2java
 */
@Alias("loan_address")
public class LoanAddress implements java.io.Serializable {
	private Integer address_id;
	private String province;
	private String city;
	private String detail_address;

	public LoanAddress() {
	}

	public LoanAddress(Integer address_id, String province, String city, String detail_address) {
		this.address_id = address_id;
		this.province = province;
		this.city = city;
		this.detail_address = detail_address;
	}

	public Integer getAddress_id() {
		return address_id;
	}

	public void setAddress_id(Integer address_id) {
		this.address_id = address_id;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDetail_address() {
		return detail_address;
	}

	public void setDetail_address(String detail_address) {
		this.detail_address = detail_address;
	}
}
