package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanCompany generated by hbm2java
 */
@Alias("loan_company")
public class LoanCompany implements java.io.Serializable {

	private Integer loan_company_id;
	private Integer user_id;
	private Integer loan_id;
	private Integer loan_corporation_id;
	private String com_full_name;
	private BigDecimal annual_revenue;
	private BigDecimal annual_profit;
	private String email;
	private Integer working_address_id;
	private Byte com_type;
	private Byte industry;
	private Byte scale;
	private Short operation_year;
	private String com_telephone;
	private Date create_time;
	private Date update_time;

	public LoanCompany() {
	}

	public LoanCompany(Integer loan_company_id, Integer user_id, Integer loan_id, Integer loan_corporation_id, String com_full_name, BigDecimal annual_revenue, BigDecimal annual_profit, String email, Integer working_address_id, Byte com_type, Byte industry, Byte scale, Short operation_year, String com_telephone, Date create_time, Date update_time) {
		this.loan_company_id = loan_company_id;
		this.user_id = user_id;
		this.loan_id = loan_id;
		this.loan_corporation_id = loan_corporation_id;
		this.com_full_name = com_full_name;
		this.annual_revenue = annual_revenue;
		this.annual_profit = annual_profit;
		this.email = email;
		this.working_address_id = working_address_id;
		this.com_type = com_type;
		this.industry = industry;
		this.scale = scale;
		this.operation_year = operation_year;
		this.com_telephone = com_telephone;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public Integer getLoan_company_id() {
		return loan_company_id;
	}

	public void setLoan_company_id(Integer loan_company_id) {
		this.loan_company_id = loan_company_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public Integer getLoan_id() {
		return loan_id;
	}

	public void setLoan_id(Integer loan_id) {
		this.loan_id = loan_id;
	}

	public Integer getLoan_corporation_id() {
		return loan_corporation_id;
	}

	public void setLoan_corporation_id(Integer loan_corporation_id) {
		this.loan_corporation_id = loan_corporation_id;
	}

	public String getCom_full_name() {
		return com_full_name;
	}

	public void setCom_full_name(String com_full_name) {
		this.com_full_name = com_full_name;
	}

	public BigDecimal getAnnual_revenue() {
		return annual_revenue;
	}

	public void setAnnual_revenue(BigDecimal annual_revenue) {
		this.annual_revenue = annual_revenue;
	}

	public BigDecimal getAnnual_profit() {
		return annual_profit;
	}

	public void setAnnual_profit(BigDecimal annual_profit) {
		this.annual_profit = annual_profit;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getWorking_address_id() {
		return working_address_id;
	}

	public void setWorking_address_id(Integer working_address_id) {
		this.working_address_id = working_address_id;
	}

	public Byte getCom_type() {
		return com_type;
	}

	public void setCom_type(Byte com_type) {
		this.com_type = com_type;
	}

	public Byte getIndustry() {
		return industry;
	}

	public void setIndustry(Byte industry) {
		this.industry = industry;
	}

	public Byte getScale() {
		return scale;
	}

	public void setScale(Byte scale) {
		this.scale = scale;
	}

	public Short getOperation_year() {
		return operation_year;
	}

	public void setOperation_year(Short operation_year) {
		this.operation_year = operation_year;
	}

	public String getCom_telephone() {
		return com_telephone;
	}

	public void setCom_telephone(String com_telephone) {
		this.com_telephone = com_telephone;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
