package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

/**
 * LoanBorrowerRelationship generated by hbm2java
 */
@Alias("loan_borrower_relationship")
public class LoanBorrowerRelationship implements java.io.Serializable {

	private Integer borrower_relationship_id;
	private Integer borrower_id;
	private Byte borrower_type;
	private String ralation_name;
	private String relationship;
	private Byte relation_type;
	private String mobile_phone;

	public LoanBorrowerRelationship() {
	}

	public LoanBorrowerRelationship(Integer borrower_relationship_id, Integer borrower_id, Byte borrower_type, String ralation_name, String relationship, Byte relation_type, String mobile_phone) {
		this.borrower_relationship_id = borrower_relationship_id;
		this.borrower_id = borrower_id;
		this.borrower_type = borrower_type;
		this.ralation_name = ralation_name;
		this.relationship = relationship;
		this.relation_type = relation_type;
		this.mobile_phone = mobile_phone;
	}

	public Integer getBorrower_relationship_id() {
		return borrower_relationship_id;
	}

	public void setBorrower_relationship_id(Integer borrower_relationship_id) {
		this.borrower_relationship_id = borrower_relationship_id;
	}

	public Integer getBorrower_id() {
		return borrower_id;
	}

	public void setBorrower_id(Integer borrower_id) {
		this.borrower_id = borrower_id;
	}

	public Byte getBorrower_type() {
		return borrower_type;
	}

	public void setBorrower_type(Byte borrower_type) {
		this.borrower_type = borrower_type;
	}

	public String getRalation_name() {
		return ralation_name;
	}

	public void setRalation_name(String ralation_name) {
		this.ralation_name = ralation_name;
	}

	public String getRelationship() {
		return relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	public Byte getRelation_type() {
		return relation_type;
	}

	public void setRelation_type(Byte relation_type) {
		this.relation_type = relation_type;
	}

	public String getMobile_phone() {
		return mobile_phone;
	}

	public void setMobile_phone(String mobile_phone) {
		this.mobile_phone = mobile_phone;
	}
}
