package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanDetail generated by hbm2java
 */
@Alias("loan_detail")
public class LoanDetail implements java.io.Serializable {

	private Integer loan_id;
	@NotNull
//	@KeyInTable(value = IAccountUserDao.class,message = "无此用户...")
	private Integer user_id;
	private String loan_title;
	private BigDecimal loan_amount;
	private String loan_usage;
	private Short loan_period;
	private BigDecimal annual_rate;
	private Short repay_period;
	private Byte repay_type;
	private Short tender_day;
	private String loan_desc;
	private Byte loan_status;
	private Byte borrower_type;
	private Date create_time;
	private Date update_time;
	private String remark;
	private BigDecimal loan_rate;

	public LoanDetail() {
	}

	public LoanDetail(Integer loan_id) {
		this.loan_id = loan_id;
	}

/*	public LoanDetail(Integer loan_id, Integer user_id, String loan_title, BigDecimal loan_amount, Byte loan_usage, Short loan_period, BigDecimal annual_rate, Short repay_period, Byte repay_type, Short tender_day, String loan_desc, Byte loan_status, Byte borrower_type, Date create_time, Date update_time, String remark, BigDecimal loan_rate) {
		this.loan_id = loan_id;
		this.user_id = user_id;
		this.loan_title = loan_title;
		this.loan_amount = loan_amount;
		this.loan_usage = loan_usage;
		this.loan_period = loan_period;
		this.annual_rate = annual_rate;
		this.repay_period = repay_period;
		this.repay_type = repay_type;
		this.tender_day = tender_day;
		this.loan_desc = loan_desc;
		this.loan_status = loan_status;
		this.borrower_type = borrower_type;
		this.create_time = create_time;
		this.update_time = update_time;
		this.remark = remark;
		this.loan_rate = loan_rate;
	}*/

	public Integer getLoan_id() {
		return loan_id;
	}

	public void setLoan_id(Integer loan_id) {
		this.loan_id = loan_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public String getLoan_title() {
		return loan_title;
	}

	public void setLoan_title(String loan_title) {
		this.loan_title = loan_title;
	}

	public BigDecimal getLoan_amount() {
		return loan_amount;
	}

	public void setLoan_amount(BigDecimal loan_amount) {
		this.loan_amount = loan_amount;
	}

	public String getLoan_usage() {
		return loan_usage;
	}

	public void setLoan_usage(String loan_usage) {
		this.loan_usage = loan_usage;
	}

	public Short getLoan_period() {
		return loan_period;
	}

	public void setLoan_period(Short loan_period) {
		this.loan_period = loan_period;
	}

	public BigDecimal getAnnual_rate() {
		return annual_rate;
	}

	public void setAnnual_rate(BigDecimal annual_rate) {
		this.annual_rate = annual_rate;
	}

	public Short getRepay_period() {
		return repay_period;
	}

	public void setRepay_period(Short repay_period) {
		this.repay_period = repay_period;
	}

	public Byte getRepay_type() {
		return repay_type;
	}

	public void setRepay_type(Byte repay_type) {
		this.repay_type = repay_type;
	}

	public Short getTender_day() {
		return tender_day;
	}

	public void setTender_day(Short tender_day) {
		this.tender_day = tender_day;
	}

	public String getLoan_desc() {
		return loan_desc;
	}

	public void setLoan_desc(String loan_desc) {
		this.loan_desc = loan_desc;
	}

	public Byte getLoan_status() {
		return loan_status;
	}

	public void setLoan_status(Byte loan_status) {
		this.loan_status = loan_status;
	}

	public Byte getBorrower_type() {
		return borrower_type;
	}

	public void setBorrower_type(Byte borrower_type) {
		this.borrower_type = borrower_type;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getLoan_rate() {
		return loan_rate;
	}

	public void setLoan_rate(BigDecimal loan_rate) {
		this.loan_rate = loan_rate;
	}
}
