package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * ManageLog generated by hbm2java
 */
@Alias("manage_log")
public class ManageLog implements java.io.Serializable {

	private Integer id;
	private Integer deal_id;
	private Integer user_id;
	private String user_name;
	private String module;
	private String action;
	private String user_ip;
	private Date oper_time;

	public ManageLog() {
	}

	public ManageLog(Integer id, Integer deal_id, Integer user_id, String user_name, String module, String action, String user_ip, Date oper_time) {
		this.id = id;
		this.deal_id = deal_id;
		this.user_id = user_id;
		this.user_name = user_name;
		this.module = module;
		this.action = action;
		this.user_ip = user_ip;
		this.oper_time = oper_time;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDeal_id() {
		return deal_id;
	}

	public void setDeal_id(Integer deal_id) {
		this.deal_id = deal_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	public String getModule() {
		return module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getUser_ip() {
		return user_ip;
	}

	public void setUser_ip(String user_ip) {
		this.user_ip = user_ip;
	}

	public Date getOper_time() {
		return oper_time;
	}

	public void setOper_time(Date oper_time) {
		this.oper_time = oper_time;
	}
}
