package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * ProductAllot generated by hbm2java
 */
@Alias("product_allot")
public class ProductAllot implements java.io.Serializable {

	private int product_id;
	@NotNull
	private int manager_id;
	@NotNull
	private int worker_id;
	private Date create_time;
	private Date update_time;

	public ProductAllot() {
	}

	public ProductAllot(int product_id, int manager_id, int worker_id, Date create_time, Date update_time) {
		this.product_id = product_id;
		this.manager_id = manager_id;
		this.worker_id = worker_id;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public int getProduct_id() {
		return product_id;
	}

	public void setProduct_id(int product_id) {
		this.product_id = product_id;
	}

	public int getManager_id() {
		return manager_id;
	}

	public void setManager_id(int manager_id) {
		this.manager_id = manager_id;
	}

	public int getWorker_id() {
		return worker_id;
	}

	public void setWorker_id(int worker_id) {
		this.worker_id = worker_id;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
