package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * SysLoanCertificateType generated by hbm2java
 */
@Alias("sys_loan_certificate_type")
public class SysLoanCertificateType implements java.io.Serializable {

	private int sys_certificate_type_id;
	private Short borrower_type;
	private String type_name;
	private Date create_time;

	public SysLoanCertificateType() {
	}

	public SysLoanCertificateType(int sys_certificate_type_id, Short borrower_type, String type_name, Date create_time) {
		this.sys_certificate_type_id = sys_certificate_type_id;
		this.borrower_type = borrower_type;
		this.type_name = type_name;
		this.create_time = create_time;
	}

	public int getSys_certificate_type_id() {
		return sys_certificate_type_id;
	}

	public void setSys_certificate_type_id(int sys_certificate_type_id) {
		this.sys_certificate_type_id = sys_certificate_type_id;
	}

	public Short getBorrower_type() {
		return borrower_type;
	}

	public void setBorrower_type(Short borrower_type) {
		this.borrower_type = borrower_type;
	}

	public String getType_name() {
		return type_name;
	}

	public void setType_name(String type_name) {
		this.type_name = type_name;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
