package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.util.Date;

/**
 * SysLoanCertificate generated by hbm2java
 */
@Alias("sys_loan_certificate")
public class SysLoanCertificate implements java.io.Serializable {

	private Integer sys_certificate_id;
	private Integer loan_id;
	private Integer certificate_type_id;
	private String file_path;
	private Byte file_type;
	private String qq_number;
	private String weixi_number;
	private String weibo_number;
	private Date create_time;

	public SysLoanCertificate() {
	}

	public SysLoanCertificate(Integer sys_certificate_id, Integer loan_id, Integer certificate_type_id, String file_path, Byte file_type, String qq_number, String weixi_number, String weibo_number, Date create_time) {
		this.sys_certificate_id = sys_certificate_id;
		this.loan_id = loan_id;
		this.certificate_type_id = certificate_type_id;
		this.file_path = file_path;
		this.file_type = file_type;
		this.qq_number = qq_number;
		this.weixi_number = weixi_number;
		this.weibo_number = weibo_number;
		this.create_time = create_time;
	}

	public Integer getSys_certificate_id() {
		return sys_certificate_id;
	}

	public void setSys_certificate_id(Integer sys_certificate_id) {
		this.sys_certificate_id = sys_certificate_id;
	}

	public Integer getLoan_id() {
		return loan_id;
	}

	public void setLoan_id(Integer loan_id) {
		this.loan_id = loan_id;
	}

	public Integer getCertificate_type_id() {
		return certificate_type_id;
	}

	public void setCertificate_type_id(Integer certificate_type_id) {
		this.certificate_type_id = certificate_type_id;
	}

	public String getFile_path() {
		return file_path;
	}

	public void setFile_path(String file_path) {
		this.file_path = file_path;
	}

	public Byte getFile_type() {
		return file_type;
	}

	public void setFile_type(Byte file_type) {
		this.file_type = file_type;
	}

	public String getQq_number() {
		return qq_number;
	}

	public void setQq_number(String qq_number) {
		this.qq_number = qq_number;
	}

	public String getWeixi_number() {
		return weixi_number;
	}

	public void setWeixi_number(String weixi_number) {
		this.weixi_number = weixi_number;
	}

	public String getWeibo_number() {
		return weibo_number;
	}

	public void setWeibo_number(String weibo_number) {
		this.weibo_number = weibo_number;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
