package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * SysModule generated by hbm2java
 */
@Alias("sys_module")
public class SysModule implements java.io.Serializable {

	private Integer moduleId;
	@NotNull
	private String moduleName;
	private String moduleUrl;
	private Integer parentId;
	private Date createTime;
	private Date updateTime;

	public SysModule() {
	}

	public SysModule(String moduleName) {
		this.moduleName = moduleName;
	}

	public SysModule(String moduleName, String moduleUrl, Integer parentId,
			Date createTime, Date updateTime) {
		this.moduleName = moduleName;
		this.moduleUrl = moduleUrl;
		this.parentId = parentId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	public String getModuleUrl() {
		return this.moduleUrl;
	}

	public void setModuleUrl(String moduleUrl) {
		this.moduleUrl = moduleUrl;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
