package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * SysMailLog generated by hbm2java
 */
@Alias("sys_mail_log")
public class SysMailLog implements java.io.Serializable {

	private Integer mail_id;
	@NotNull
	private String from_mail;
	@NotNull
	private String to_mail;
	@NotNull
	private String mail_subject;
	private String parameter;
	@NotNull
	private String template;
	@NotNull
	private byte mail_status;
	private Date send_time;
	@NotNull
	private Date create_time;
	@NotNull
	private Date update_time;

	public SysMailLog() {
	}

	public SysMailLog(Integer mail_id, String from_mail, String to_mail, String mail_subject, String parameter, String template, byte mail_status, Date send_time, Date create_time, Date update_time) {
		this.mail_id = mail_id;
		this.from_mail = from_mail;
		this.to_mail = to_mail;
		this.mail_subject = mail_subject;
		this.parameter = parameter;
		this.template = template;
		this.mail_status = mail_status;
		this.send_time = send_time;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public Integer getMail_id() {
		return mail_id;
	}

	public void setMail_id(Integer mail_id) {
		this.mail_id = mail_id;
	}

	public String getFrom_mail() {
		return from_mail;
	}

	public void setFrom_mail(String from_mail) {
		this.from_mail = from_mail;
	}

	public String getTo_mail() {
		return to_mail;
	}

	public void setTo_mail(String to_mail) {
		this.to_mail = to_mail;
	}

	public String getMail_subject() {
		return mail_subject;
	}

	public void setMail_subject(String mail_subject) {
		this.mail_subject = mail_subject;
	}

	public String getParameter() {
		return parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	public String getTemplate() {
		return template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public byte getMail_status() {
		return mail_status;
	}

	public void setMail_status(byte mail_status) {
		this.mail_status = mail_status;
	}

	public Date getSend_time() {
		return send_time;
	}

	public void setSend_time(Date send_time) {
		this.send_time = send_time;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}
}
