package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;

/**
 * SysRoleModule generated by hbm2java
 */
@Alias("sys_role_module")
public class SysRoleModule implements java.io.Serializable {
@NotNull
	private Integer roleId;
	@NotNull
	private  Integer moduleId;
	private  Integer rights;

	public SysRoleModule() {
	}

	public SysRoleModule(Integer roleId, Integer moduleId, Integer rights) {
		this.roleId = roleId;
		this.moduleId = moduleId;
		this.rights = rights;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getModuleId() {
		return moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	public Integer getRights() {
		return rights;
	}

	public void setRights(Integer rights) {
		this.rights = rights;
	}
}
