package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * SysSmrzImage generated by hbm2java
 */
@Alias("sys_smrz_image")
public class SysSmrzImage implements java.io.Serializable {

	private Integer image_id;
	@NotNull
	private String identitycard;
	private byte[] card_image;
	@NotNull
	private Date create_time;

	public SysSmrzImage() {
	}

	public SysSmrzImage(Integer image_id, String identitycard, byte[] card_image, Date create_time) {
		this.image_id = image_id;
		this.identitycard = identitycard;
		this.card_image = card_image;
		this.create_time = create_time;
	}

	public Integer getImage_id() {
		return image_id;
	}

	public void setImage_id(Integer image_id) {
		this.image_id = image_id;
	}

	public String getIdentitycard() {
		return identitycard;
	}

	public void setIdentitycard(String identitycard) {
		this.identitycard = identitycard;
	}

	public byte[] getCard_image() {
		return card_image;
	}

	public void setCard_image(byte[] card_image) {
		this.card_image = card_image;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}
}
