package com.hhn.pojo;

// Generated 2014-12-2 15:40:14 by Hibernate Tools 3.4.0.CR1

import org.apache.ibatis.type.Alias;

import java.math.BigDecimal;
import java.util.Date;

/**
 * AccountUser generated by hbm2java
 */
@Alias("trans_info")
public class TransInfo implements java.io.Serializable,Cloneable {
	private String trans_info_id;
	private Integer user_id;
	private String card_id;
	private String bank_user;
	private BigDecimal trans_money;
	private String content;
	private Date create_time;
	private String third_sn;
	private Integer socket_type;
	private Integer operation_type;
	private Integer actual_id;

	public TransInfo(){}
	public TransInfo(String trans_info_id) {
		this.trans_info_id = trans_info_id;
	}

	public String getTrans_info_id() {
		return trans_info_id;
	}

	public void setTrans_info_id(String trans_info_id) {
		this.trans_info_id = trans_info_id;
	}

	public Integer getUser_id() {
		return user_id;
	}

	public void setUser_id(Integer user_id) {
		this.user_id = user_id;
	}

	public String getCard_id() {
		return card_id;
	}

	public void setCard_id(String card_id) {
		this.card_id = card_id;
	}

	public String getBank_user() {
		return bank_user;
	}

	public void setBank_user(String bank_user) {
		this.bank_user = bank_user;
	}

	public BigDecimal getTrans_money() {
		return trans_money;
	}

	public void setTrans_money(BigDecimal trans_money) {
		this.trans_money = trans_money;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public String getThird_sn() {
		return third_sn;
	}

	public void setThird_sn(String third_sn) {
		this.third_sn = third_sn;
	}

	public Integer getSocket_type() {
		return socket_type;
	}

	public void setSocket_type(Integer socket_type) {
		this.socket_type = socket_type;
	}

	public Integer getOperation_type() {
		return operation_type;
	}

	public void setOperation_type(Integer operation_type) {
		this.operation_type = operation_type;
	}

	public Integer getActual_id() {
		return actual_id;
	}

	public void setActual_id(Integer actual_id) {
		this.actual_id = actual_id;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		Object obj=super.clone();
		if(obj instanceof TransInfo)
			return (TransInfo)obj;
		return new TransInfo();
	}
}
